# Ruff configuration

target-version = "py312"
line-length = 100

[lint]
# Select warn level - not strict
select = ["E", "F", "W"]
ignore = [
    "E501",  # line too long
    "E722",  # bare except
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # unused import
"tests/*" = ["E501"]
