"""Stub for pandas package"""
from typing import Any

class Series:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def empty(self) -> bool: ...
    @property
    def str(self) -> StringMethods: ...
    @property
    def iloc(self) -> Any: ...
    @property
    def loc(self) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __float__(self) -> float: ...
    def astype(self, dtype: str) -> Series: ...
    def isna(self) -> Series: ...
    def notna(self) -> Series: ...

class StringMethods:
    def endswith(self, suffix: str) -> Series: ...
    def startswith(self, prefix: str) -> Series: ...

class DataFrame:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy(self) -> DataFrame: ...
    @property
    def empty(self) -> bool: ...
    @property
    def columns(self) -> Any: ...
    @property
    def loc(self) -> Any: ...
    def __getitem__(self, key: Any) -> Series: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def items(self) -> Any: ...
    def iterrows(self) -> Any: ...
    def sort_values(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def drop_duplicates(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def rename(self, *args: Any, **kwargs: Any) -> DataFrame: ...

def isna(value: Any) -> Any: ...
def notna(value: Any) -> Any: ...
def to_datetime(arg: Any, *args: Any, **kwargs: Any) -> Any: ...
