"""Stub for tushare package"""
from typing import Any

def set_token(token: str) -> None: ...

class ProApi:
    def __call__(self, token: str | None = None) -> ProApi: ...
    def balancesheet(self, ts_code: str, start_date: str | None = None, end_date: str | None = None) -> Any: ...
    def income(self, ts_code: str, start_date: str | None = None, end_date: str | None = None) -> Any: ...
    def cashflow(self, ts_code: str, start_date: str | None = None, end_date: str | None = None) -> Any: ...
    def fina_indicator(self, ts_code: str, start_date: str | None = None, end_date: str | None = None) -> Any: ...
    def daily_basic(self, ts_code: str, trade_date: str | None = None) -> Any: ...
    def daily(self, ts_code: str, trade_date: str | None = None) -> Any: ...

def pro_api(token: str | None = None) -> ProApi: ...
