"""Stub for vi_core package"""
from typing import Any

class ViCorePlugin:
    def __init__(self) -> None: ...
    def set_plugin_manager(self, pm: Any) -> None: ...
    def get_vi_pm(self) -> Any: ...
    @property
    def commands(self) -> list[str]: ...
    def get_capabilities(self) -> dict[str, Any]: ...
    def on_load(self) -> None: ...
    def handle(self, task: Any) -> dict[str, Any]: ...
    def vi_commands(self) -> list[str]: ...
    def vi_fields(self) -> dict[str, Any]: ...
    def vi_handle(self, command: str, args: dict[str, Any]) -> dict[str, Any]: ...
    def _list_fields(self, args: dict[str, Any]) -> dict[str, Any]: ...
    def _query(self, args: dict[str, Any]) -> dict[str, Any]: ...
    def _list_calculators(self, args: dict[str, Any]) -> dict[str, Any]: ...
    def on_unload(self) -> None: ...

class ValueInvestmentSpecs:
    ...

plugin: ViCorePlugin
