"""Stub for vi_calculators package"""
from typing import Any

class CalculatorLoaderPlugin:
    def __init__(self) -> None: ...
    def vi_list_calculators(self) -> list[dict[str, Any]]: ...
    def vi_run_calculator(self, name: str, data: dict[str, Any], config: dict[str, Any]) -> dict[str, Any] | None: ...
    def vi_register_calculator(self, name: str, code: str, required_fields: list[str], namespace: str, description: str = "") -> dict[str, Any]: ...

plugin: CalculatorLoaderPlugin
